### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by neekolas** [xmtp/xmtpd#104]
We need to set up a Github action that builds `dev/docker/Dockerfile` and publishes it to the Github Container Registry.

You can see an example from one of our other repos [here](https://github.com/xmtp/libxmtp/blob/533efcb221cfa334198a0d0b81131b0175c4f5f2/.github/workflows/deploy-validation-server.yml#L18-L42).

Once we have a Terraform configuration set up which takes the Docker image as a variable, we can use the `xmtp-labs/terraform-deployer@v1` Github action to automatically update the variable and trigger a new Terraform Cloud run on merge to main.

**Comment by mkysel** [comment]
Sounds pretty easy!
