### ISSUE TITLE
Trigger infra version bump from xmtpd build

### ISSUE THREAD

**Issue by mkysel** [xmtp/xmtpd#201]
ECS does not automatically deploy the newest version. There has to be a change in the config such as the SHA of the docker image for ECS to deploy a new version. This is done in node-go as well.

**Comment by neekolas** [comment]
The deployment config in libxmtp for the mls validation service can be nearly copy/pasted since it also uses GHCR instead of Docker Hub.

**Comment by mkysel** [comment]
I haven't done this yet, because I need to re-generate the keys and copy paste them to all the various xmtp repositories.
